name: Publish to hex.pm

on:
  release:
    types:
      - created
  # run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Erlang
        uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: "27.0"
          gleam-version: "1.9.0"
          rebar3-version: "3"

      - name: Build and publish package
        run: |
          gleam deps download
          gleam build
          gleam publish -y
        env:
          HEXPM_API_KEY: ${{ secrets.HEXPM_API_KEY }}
